const fs = require("fs");
const base = "C:/Users/roman.fetisov/Desktop/Box/industry/Web/Dashboards/mcp-server/scripts";
const d = JSON.parse(fs.readFileSync(base + "/get-4.1_WC_Piece_T_Control.json", "utf8"));
const q = d.dataSources[0].dataBase.queries[0];
console.log("column id samples:");
for (const c of q.columns.slice(0, 12)) console.log("  id=", c.id, "tableId=", c.tableId, "name=", c.name, "type=", c.valueType && c.valueType.name);
const positives = q.columns.filter((c) => Number(c.id) > 0);
console.log("positive id columns:", positives.length, "negative:", q.columns.length - positives.length);
for (const c of positives) console.log("  POS id=", c.id, "tableId=", c.tableId, "name=", c.name);
const dfIds = new Set(t.dataFields.map((df) => Number(df.columnId)).filter((x) => x > 0));
const colPos = new Set(positives.map((c) => Number(c.id)));
console.log("df positive ids in query.columns?", [...dfIds].every((x) => colPos.has(x)));
console.log("df positives:", [...dfIds].join(","), "query positives:", [...colPos].join(","));
const t = d.components.find((c) => c.type === "table");
console.log("table comp df summaries:");
for (const df of t.dataFields.slice(0, 8)) console.log("  df.id=", df.id, "col=", df.columnId, "te=", df.typeEnum);
